# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:52
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import sis.studentdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated', models.BooleanField(default=False)),
                ('graduation_date', models.DateField(blank=True, help_text='Expected or actual graduation date', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('college_override', models.BooleanField(default=False, help_text='If checked, college enrollment data will not set college and graduated automatically.')),
                ('program_years', models.CharField(blank=True, choices=[('4', '4-year or higher institution'), ('2', '2-year institution'), ('L', 'less than 2-year institution')], max_length=1, null=True)),
                ('semesters', models.CharField(blank=True, help_text='Number of semesters or trimesters.', max_length=5)),
                ('on_track', models.BooleanField(default=False, help_text='On track to graduate')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='AlumniAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('alumni', models.ManyToManyField(blank=True, to='alumni.Alumni')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(blank=True, choices=[('Personal', 'Personal'), ('School', 'School'), ('Work', 'Work'), ('Other', 'Other')], max_length=255, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniNoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('type', models.CharField(blank=True, choices=[('H', 'Home'), ('C', 'Cell'), ('W', 'Work'), ('O', 'Other')], max_length=255, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Alumni Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', sis.studentdb.models.CAUSStateField(blank=True, max_length=2)),
                ('type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('program_years', models.CharField(blank=True, choices=[('4', '4-year or higher institution'), ('2', '2-year institution'), ('L', 'less than 2-year institution')], max_length=1, null=True)),
                ('begin', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('end', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('status', models.CharField(blank=True, choices=[('F', 'Full-time'), ('H', 'Half-time'), ('L', 'Less than half-time'), ('A', 'Leave of absence'), ('W', 'Withdrawn'), ('D', 'Deceased')], max_length=1, null=True)),
                ('graduated', models.BooleanField(default=False)),
                ('graduation_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('degree_title', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('college_sequence', models.IntegerField(blank=True, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.College')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('semesters', models.DecimalField(blank=True, decimal_places=3, help_text='Number of semesters/trimesters at this college.', max_digits=5, max_length=5, null=True)),
                ('from_enrollment', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.College')),
            ],
        ),
        migrations.AddField(
            model_name='alumninote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alumni.AlumniNoteCategory'),
        ),
        migrations.AddField(
            model_name='alumninote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumni',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_student', to='alumni.College'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.AlumniStatus'),
        ),
    ]
