# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        ('studentdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='studentdb.Student'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='withdrawls',
            field=models.ManyToManyField(through='alumni.Withdrawl', to='alumni.College'),
        ),
    ]
