# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0002_auto_20181002_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcardaccess',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='reportcardaccess',
            name='description',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reportcardaccess',
            name='sections',
            field=models.ManyToManyField(help_text='Choose one of Subject or Section', to='indysis_reportcard.ReportCardSection'),
        ),
        migrations.AddField(
            model_name='reportcardaccess',
            name='student_classes',
            field=models.ManyToManyField(to='studentdb.StudentClass'),
        ),
        migrations.AddField(
            model_name='reportcardaccess',
            name='subjects',
            field=models.ManyToManyField(help_text='Choose one of Subject or Section', to='indysis_reportcard.ReportCardSubject'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcardaccess',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='reportcardaccess',
            name='section',
        ),
        migrations.RemoveField(
            model_name='reportcardaccess',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reportcardaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportcardaccess',
            name='year',
        ),
    ]
