# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0003_auto_20181002_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardaccess',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='studentdb.Faculty'),
        ),
        migrations.AlterField(
            model_name='reportcardaccess',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Choose one of Subject or Section', to='indysis_reportcard.ReportCardSection'),
        ),
        migrations.AlterField(
            model_name='reportcardaccess',
            name='student_classes',
            field=models.ManyToManyField(blank=True, to='studentdb.StudentClass'),
        ),
        migrations.AlterField(
            model_name='reportcardaccess',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Choose one of Subject or Section', to='indysis_reportcard.ReportCardSubject'),
        ),
    ]
