# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 22:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0009_reportcard_grade_level_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardentry',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indysis_reportcard.GradingSchemeLevelChoice', verbose_name='2nd Mark'),
        ),
        migrations.AddField(
            model_name='reportcardentry',
            name='second_percentile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='2nd Mark'),
        ),
        migrations.AddField(
            model_name='reportcardsection',
            name='second_gradingscheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indysis_reportcard.GradingScheme'),
        ),
    ]
