# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0012_remove_reportcardstrand_comments_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardSharedTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('coverpage_template', models.TextField(blank=True, null=True)),
                ('header_template', models.TextField(blank=True, null=True)),
                ('footer_template', models.TextField(blank=True, null=True)),
                ('body_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reportcardtemplate',
            name='shared_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCardSharedTemplate'),
        ),
    ]
