# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0013_auto_20181116_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingschemelevel',
            options={'ordering': ['sortorder']},
        ),
        migrations.AlterModelOptions(
            name='gradingschemelevelchoice',
            options={'ordering': ['sortorder']},
        ),
        migrations.AlterModelOptions(
            name='reportcardsection',
            options={'ordering': ['sortorder']},
        ),
        migrations.AlterModelOptions(
            name='reportcardstrand',
            options={'ordering': ['sortorder']},
        ),
        migrations.AlterModelOptions(
            name='reportcardsubject',
            options={'ordering': ['sortorder']},
        ),
    ]
