# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0015_auto_20181117_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardsection',
            name='page_break_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcardterm',
            name='title',
            field=models.CharField(default='', help_text='Title for report card', max_length=255),
        ),
        migrations.AddField(
            model_name='reportcardterm',
            name='title_en',
            field=models.CharField(default='', help_text='Title for report card', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportcardterm',
            name='title_fr',
            field=models.CharField(default='', help_text='Title for report card', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportcardterm',
            name='displabel',
            field=models.CharField(default='1', help_text='Value to show on data entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportcardterm',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name as shown on report cards', max_length=80),
        ),
        migrations.AlterField(
            model_name='reportcardterm',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='Name as shown on report cards', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reportcardterm',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='Name as shown on report cards', max_length=80, null=True),
        ),
    ]
