# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0016_auto_20181117_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingscheme',
            name='min_value',
            field=models.IntegerField(default=0, help_text='Minimum value for percentile mode'),
        ),
    ]
