# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0017_gradingscheme_min_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'verbose_name': 'Report card'},
        ),
        migrations.AlterModelOptions(
            name='reportcardentry',
            options={'verbose_name': 'Report card mark data'},
        ),
        migrations.AlterModelOptions(
            name='reportcardsection',
            options={'ordering': ['template__name', 'sortorder'], 'verbose_name': 'Template section'},
        ),
        migrations.AlterModelOptions(
            name='reportcardsharedtemplate',
            options={'verbose_name': 'Shared template'},
        ),
        migrations.AlterModelOptions(
            name='reportcardstrand',
            options={'ordering': ['sortorder'], 'verbose_name': 'Template strand'},
        ),
        migrations.AlterModelOptions(
            name='reportcardsubject',
            options={'ordering': ['sortorder'], 'verbose_name': 'Template subject'},
        ),
        migrations.AlterModelOptions(
            name='reportcardsubmission',
            options={'verbose_name': 'Report card submission'},
        ),
        migrations.AlterModelOptions(
            name='reportcardtemplate',
            options={'verbose_name': 'Templates'},
        ),
        migrations.AlterModelOptions(
            name='reportcardtemplateimage',
            options={'verbose_name': 'Template image'},
        ),
        migrations.AlterModelOptions(
            name='reportcardterm',
            options={'verbose_name': 'Term'},
        ),
        migrations.AlterModelOptions(
            name='reportcardyeargradecontent',
            options={'verbose_name': 'Static report card content', 'verbose_name_plural': 'Static report card content'},
        ),
    ]
