# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0018_auto_20181118_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcardtemplate',
            options={'verbose_name': 'Template'},
        ),
    ]
