# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0019_auto_20181118_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardentry',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.GradingSchemeLevelChoice', verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='reportcardentry',
            name='reportcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCard'),
        ),
        migrations.AlterField(
            model_name='reportcardentry',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice', to='indysis_reportcard.GradingSchemeLevelChoice', verbose_name='2nd Mark'),
        ),
        migrations.AlterField(
            model_name='reportcardentry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCardSection'),
        ),
        migrations.AlterField(
            model_name='reportcardentry',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCardStrand'),
        ),
        migrations.AlterField(
            model_name='reportcardentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCardSubject'),
        ),
    ]
