# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_reportcard', '0020_auto_20181120_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardtemplate',
            name='shared_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indysis_reportcard.ReportCardSharedTemplate'),
        ),
    ]
