# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMatch',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('simple_import.columnmatch',),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('simple_import.importlog',),
        ),
    ]
