# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='"Present" will not be saved but may show as a teacher option.', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short code used on attendance reports. Ex: A might be the code for the name Absent', max_length=10, unique=True)),
                ('teacher_selectable', models.BooleanField(default=False)),
                ('excused', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False, help_text='Some statistics need to add various types of absent statuses, such as the number in parentheses in daily attendance.')),
                ('tardy', models.BooleanField(default=False, help_text='Some statistics need to add various types of tardy statuses, such as the number in parentheses in daily attendance.')),
                ('half', models.BooleanField(default=False, help_text='Half attendance when counting. DO NOT check off absent otherwise it will double count!')),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance statuses',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='OfficeAttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('ampm', models.CharField(blank=True, choices=[('am', 'am'), ('pm', 'pm')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('private_notes', models.CharField(blank=True, max_length=500)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attn_recorder', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceStatus')),
            ],
            options={
                'ordering': ('-date', 'student'),
                'permissions': (('take_studentattendance', 'Take student attendance'), ('admin_studentattendance', 'Administer student attendance')),
            },
        ),
    ]
