# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(help_text="Start typing a student's first or last name to search", on_delete=django.db.models.deletion.CASCADE, related_name='student_attn', to='studentdb.Student'),
        ),
        migrations.AddField(
            model_name='officeattendancelog',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.GradeLevel'),
        ),
        migrations.AddField(
            model_name='officeattendancelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set([('student', 'date', 'status')]),
        ),
        migrations.AlterUniqueTogether(
            name='officeattendancelog',
            unique_together=set([('date', 'grade_level', 'ampm')]),
        ),
    ]
