# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0008_auto_20181015_2051'),
        ('attendance', '0002_auto_20180909_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeattendancelog',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentdb.StudentClass'),
        ),
    ]
