# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 03:02
from __future__ import unicode_literals

from django.db import migrations


def populate_student_class(apps, schema_editor):
    OfficeAttendanceLog = apps.get_model('attendance', 'OfficeAttendanceLog')
    for office_attendance_log in OfficeAttendanceLog.objects.all():
        student = office_attendance_log.grade_level.student_set.first()
        office_attendance_log.student_class = student.classes.first()
        office_attendance_log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_officeattendancelog_student_class'),
    ]

    operations = [
        migrations.RunPython(populate_student_class),
    ]
