# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0002_auto_20180909_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='siblings',
            field=models.ManyToManyField(related_name='_student_siblings_+', to='studentdb.Student'),
        ),
    ]
