# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0003_auto_20180910_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_student_siblings_+', to='studentdb.Student'),
        ),
    ]
