# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0004_auto_20180911_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='no_reportcard_emails',
        ),
    ]
