# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0005_remove_emergencycontact_no_reportcard_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterschoolprogramattendance',
            name='days',
        ),
        migrations.RemoveField(
            model_name='beforeschoolprogramattendance',
            name='days',
        ),
        migrations.AddField(
            model_name='afterschoolpackage',
            name='drop_in',
            field=models.BooleanField(default=False, help_text='Available on a drop-in basis'),
        ),
        migrations.AddField(
            model_name='afterschoolpackage',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='afterschoolpackage',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Unit value for drop-in programs', max_digits=6),
        ),
        migrations.AddField(
            model_name='afterschoolpackage',
            name='usage_code',
            field=models.CharField(default='1', help_text='Code to show in aftershool usage report', max_length=2),
        ),
        migrations.AddField(
            model_name='afterschoolprogramattendance',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='studentdb.AfterschoolPackage'),
        ),
        migrations.AlterField(
            model_name='afterschoolpackage',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='List Price', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='afterschoolpackage',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='studentdb.AfterschoolRegsitrationPeriod'),
        ),
    ]
