# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0006_auto_20180930_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='principal_title_en',
            field=models.CharField(default='Head of School / Directeur', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='principal_title_fr',
            field=models.CharField(default='Head of School / Directeur', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='vice_principal_title_en',
            field=models.CharField(default='Assistant Head / Directeur adjointe', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='vice_principal_title_fr',
            field=models.CharField(default='Assistant Head / Directeur adjointe', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='principal',
            field=models.ForeignKey(blank=True, help_text="This school year's headmaster/principal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='vice_principal',
            field=models.ForeignKey(blank=True, help_text="This school year's assistant headmaster/vice principal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Grade Name'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='shortname_en',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='shortname_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='shortname_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Grade Name'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='shortname_fr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Abbreviation'),
        ),
    ]
