# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema_editor):
    GradeLevel = apps.get_model('studentdb', 'GradeLevel')
    GradeLevel.objects.all().update(name_en=F('name'))
    GradeLevel.objects.all().update(shortname_en=F('shortname'))

    StudentClass = apps.get_model('studentdb', 'StudentClass')
    StudentClass.objects.all().update(name_en=F('name'))
    StudentClass.objects.all().update(shortname_en=F('shortname'))
    StudentClass.objects.all().update(description_en=F('description'))


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0007_auto_20181015_2040'),
    ]

    operations = [
        migrations.RunPython(copy_field),
    ]
