# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models

def set_order(apps, schema_editor):
    GradeLevel = apps.get_model('studentdb', 'GradeLevel')
    StudentClass = apps.get_model('studentdb', 'StudentClass')

    for grade in GradeLevel.objects.all():
        klass = StudentClass.objects.get(name=grade.name)
        klass.sortorder = grade.id
        klass.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0008_auto_20181015_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ('sortorder', 'name'), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='studentclass',
            name='sortorder',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_order),
    ]
