# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 13:29
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0009_auto_20181201_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cell',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Cellular number (used for emergency broadcasts)', max_length=128),
        ),
    ]
