# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0010_faculty_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='studentdb.Student'),
        ),
    ]
