# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0011_auto_20190805_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_account_email',
            field=models.CharField(blank=True, help_text='Full email address for school provided student email account. eg. Google Apps', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_account_initial_pw',
            field=models.CharField(blank=True, help_text='Initial password for system-created student accounts', max_length=30, null=True),
        ),
    ]
