# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentdb', '0002_auto_20180909_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleGroupSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('group_id', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='User accounts to add as group managers', related_name='googlegroup_sync_managers', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, help_text='User accounts to add as group owners', related_name='googlegroup_sync_owners', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(blank=True, help_text='User accounts to add as members', related_name='googlegroup_sync_staff', to=settings.AUTH_USER_MODEL)),
                ('synchronize_classes', models.ManyToManyField(blank=True, help_text='Which parents to synchronize', to='studentdb.StudentClass')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleGroupSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(default='success', max_length=40)),
                ('messages', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indysis_googlesync.GoogleGroupSync')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='googlegroupsynclog',
            index=models.Index(fields=['created'], name='indysis_goo_created_e7a206_idx'),
        ),
    ]
