# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_googlesync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlegroupsync',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
