# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_googlesync', '0002_auto_20181016_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('member', 'Member'), ('owner', 'Owner'), ('manager', 'Manager')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indysis_googlesync.GoogleGroupSync')),
            ],
            options={
                'ordering': ['group', 'email'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='extraemailaddress',
            unique_together=set([('group', 'email')]),
        ),
    ]
