# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_googlesync', '0004_auto_20190828_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgradeoumapping',
            name='enable_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentgradeoumapping',
            name='ou',
            field=models.CharField(max_length=100, verbose_name='OU'),
        ),
    ]
