# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_googlesync', '0005_auto_20190828_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgradeoumapping',
            name='enable_audit',
            field=models.BooleanField(default=True),
        ),
    ]
