# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 12:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentdb', '0009_auto_20181201_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('message', models.CharField(help_text='Text message body', max_length=140, validators=[django.core.validators.MinLengthValidator(4)])),
                ('status', models.CharField(default='pending', max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indysis_broadcast.Broadcast')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.EmergencyContact')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='broadcast',
            name='recipients',
            field=models.ManyToManyField(related_name='broadcast', related_query_name='recipients', through='indysis_broadcast.BroadcastRecipient', to='studentdb.EmergencyContact'),
        ),
    ]
