# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indysis_broadcast', '0002_auto_20190212_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastrecipient',
            name='message_sid',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
